[tool.setuptools.package-data]
"macro_studio" = ["*", "**/*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["macro_studio*"]
namespaces = false

[project.scripts]
macro-studio = "macro_studio.main:main"